apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: {{ .Values.service.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.service.lbPort }}
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
